#### Pandas-DataFrame And Series
Pandas is a powerful data manipulation library in Python, widely used for data analysis and data cleaning. It provides two primary data structures: Series and DataFrame. A Series is a one-dimensional array-like object, while a DataFrame is a two-dimensional, size-mutable, and potentially heterogeneous tabular data structure with labeled axes (rows and columns).

In [2]:
import pandas as pd
import numpy as np

In [3]:
## Series
##A Pandas Series is a one-dimensional array-like object that can hold any data type. It is similar to a column in a table.

import pandas as pd
data=[1,2,3,4,5]
series=pd.Series(data)
print("Series \n",series)
print(type(series))

Series 
 0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>


In [4]:
## Create a Series from dictionary
data={'a':1,'b':2,'c':3}
series_dict=pd.Series(data)
print(series_dict)


a    1
b    2
c    3
dtype: int64


In [5]:
data=[10,20,30]
index=['a','b','c']
pd.Series(data,index=index)

a    10
b    20
c    30
dtype: int64

In [2]:
## Dataframe
## create a Dataframe from a dictionary oof list

data={
    'Name':['Krish','John','Jack'],
    'Age':[25,30,45],
    'City':['Bangalore','New York','Florida']
}
df=pd.DataFrame(data)
print(df)
print(type(df))

    Name  Age       City
0  Krish   25  Bangalore
1   John   30   New York
2   Jack   45    Florida
<class 'pandas.core.frame.DataFrame'>


In [19]:
## Create a Data frame From a List of Dictionaries

data=[
    {'Name':'Krish','Age':32,'City':'Bangalore'},
    {'Name':'John','Age':34,'City':'Bangalore'},
    {'Name':'Bappy','Age':32,'City':'Bangalore'},
    {'Name':'JAck','Age':32,'City':'Bangalore'}
    
]
df=pd.DataFrame(data)
print(df)
print(type(df))

    Name  Age       City
0  Krish   32  Bangalore
1   John   34  Bangalore
2  Bappy   32  Bangalore
3   JAck   32  Bangalore
<class 'pandas.core.frame.DataFrame'>


In [10]:
import numpy as np
n = np.array(data).reshape((4,1))

In [11]:
n.shape

(4, 1)

In [21]:
df.at[0,"Name"]

'Krish'

In [3]:
df=pd.read_csv('sales_data.csv')
df.head(5)

Transaction ID        Date Product Category             Product Name  \
0           10001  2024-01-01      Electronics            iPhone 14 Pro   
1           10002  2024-01-02  Home Appliances         Dyson V11 Vacuum   
2           10003  2024-01-03         Clothing         Levi's 501 Jeans   
3           10004  2024-01-04            Books        The Da Vinci Code   
4           10005  2024-01-05  Beauty Products  Neutrogena Skincare Set   

   Units Sold  Unit Price  Total Revenue         Region Payment Method  
0           2      999.99        1999.98  North America    Credit Card  
1           1      499.99         499.99         Europe         PayPal  
2           3       69.99         209.97           Asia     Debit Card  
3           4       15.99          63.96  North America    Credit Card  
4           1       89.99          89.99         Europe         PayPal

In [11]:
df.tail(5)

Transaction ID        Date Product Category  \
235           10236  2024-08-23  Home Appliances   
236           10237  2024-08-24         Clothing   
237           10238  2024-08-25            Books   
238           10239  2024-08-26  Beauty Products   
239           10240  2024-08-27           Sports   

                                        Product Name  Units Sold  Unit Price  \
235  Nespresso Vertuo Next Coffee and Espresso Maker           1      159.99   
236                        Nike Air Force 1 Sneakers           3       90.00   
237           The Handmaid's Tale by Margaret Atwood           3       10.99   
238             Sunday Riley Luna Sleeping Night Oil           1       55.00   
239                       Yeti Rambler 20 oz Tumbler           2       29.99   

     Total Revenue         Region Payment Method  
235         159.99         Europe         PayPal  
236         270.00           Asia     Debit Card  
237          32.97  North America    Credit Card  
238          55.00         Europe         PayPal  
239          59.98           Asia    Credit Card

In [17]:
### Accessing Data From Dataframe
df

Name  Age       City
0  Krish   25  Bangalore
1   John   30   New York
2   Jack   45    Florida

In [20]:
df['Name']

0    Krish
1     John
2     Jack
Name: Name, dtype: object

In [24]:
df.loc[0]

Name        Krish
Age            25
City    Bangalore
Name: 0, dtype: object

In [30]:
df.iloc[0]

Name        Krish
Age            25
City    Bangalore
Name: 0, dtype: object

In [34]:
df

Name  Age       City
0  Krish   25  Bangalore
1   John   30   New York
2   Jack   45    Florida

In [35]:
## Accessing a specified element
df.at[2,'Age']

45

In [36]:
df.at[2,'Name']

'Jack'

In [38]:
## Accessing a specified element using iat
df.iat[2,2]

'Florida'

In [39]:
df

Name  Age       City
0  Krish   25  Bangalore
1   John   30   New York
2   Jack   45    Florida

In [40]:
### Data MAnipulation with Dataframe
df

Name  Age       City
0  Krish   25  Bangalore
1   John   30   New York
2   Jack   45    Florida

In [41]:
## Adding a column
df['Salary']=[50000,60000,70000]
df

Name  Age       City  Salary
0  Krish   25  Bangalore   50000
1   John   30   New York   60000
2   Jack   45    Florida   70000

In [46]:
## Remove a column
df.drop('Salary',axis=1,inplace=True)

In [47]:
df

Name  Age       City
0  Krish   25  Bangalore
1   John   30   New York
2   Jack   45    Florida

In [48]:
## Add age to the column
df['Age']=df['Age']+1
df

Name  Age       City
0  Krish   26  Bangalore
1   John   31   New York
2   Jack   46    Florida

In [51]:
df.drop(0,inplace=True)

In [52]:
df

Name  Age      City
1  John   31  New York
2  Jack   46   Florida

In [53]:
df=pd.read_csv('sales_data.csv')
df.head(5)

Transaction ID        Date Product Category             Product Name  \
0           10001  2024-01-01      Electronics            iPhone 14 Pro   
1           10002  2024-01-02  Home Appliances         Dyson V11 Vacuum   
2           10003  2024-01-03         Clothing         Levi's 501 Jeans   
3           10004  2024-01-04            Books        The Da Vinci Code   
4           10005  2024-01-05  Beauty Products  Neutrogena Skincare Set   

   Units Sold  Unit Price  Total Revenue         Region Payment Method  
0           2      999.99        1999.98  North America    Credit Card  
1           1      499.99         499.99         Europe         PayPal  
2           3       69.99         209.97           Asia     Debit Card  
3           4       15.99          63.96  North America    Credit Card  
4           1       89.99          89.99         Europe         PayPal

In [54]:
# Display the data types of each column
print("Data types:\n", df.dtypes)

# Describe the DataFrame
print("Statistical summary:\n", df.describe())



Data types:
 Transaction ID        int64
Date                 object
Product Category     object
Product Name         object
Units Sold            int64
Unit Price          float64
Total Revenue       float64
Region               object
Payment Method       object
dtype: object
Statistical summary:
        Transaction ID  Units Sold   Unit Price  Total Revenue
count       240.00000  240.000000   240.000000     240.000000
mean      10120.50000    2.158333   236.395583     335.699375
std          69.42622    1.322454   429.446695     485.804469
min       10001.00000    1.000000     6.500000       6.500000
25%       10060.75000    1.000000    29.500000      62.965000
50%       10120.50000    2.000000    89.990000     179.970000
75%       10180.25000    3.000000   249.990000     399.225000
max       10240.00000   10.000000  3899.990000    3899.990000


In [55]:
df.describe()

Transaction ID  Units Sold   Unit Price  Total Revenue
count       240.00000  240.000000   240.000000     240.000000
mean      10120.50000    2.158333   236.395583     335.699375
std          69.42622    1.322454   429.446695     485.804469
min       10001.00000    1.000000     6.500000       6.500000
25%       10060.75000    1.000000    29.500000      62.965000
50%       10120.50000    2.000000    89.990000     179.970000
75%       10180.25000    3.000000   249.990000     399.225000
max       10240.00000   10.000000  3899.990000    3899.990000

2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [3]:
import numpy as np

In [19]:
m = np.array([np.random.randint(0,25) for i in range(25)])

In [28]:
s = m.reshape(5,5)

In [31]:
print(s)

[[16 18 19 14 21]
 [ 4 17  3 12 12]
 [19  4 15 18 15]
 [ 6 19  3 18 11]
 [13 16  7 17  6]]


In [33]:
np.concatenate((s[0,:],s[-1,:],s[:,0],s[:,-1]))

array([16, 18, 19, 14, 21, 13, 16,  7, 17,  6, 16,  4, 19,  6, 13, 21, 12,
       15, 11,  6])

2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [49]:
a = np.random.randint(1,5,size=(4,4))
a

array([[4, 1, 1, 2],
       [4, 2, 1, 1],
       [3, 2, 4, 3],
       [3, 2, 3, 4]])

In [42]:
11+11+15+15

52

In [50]:
c = np.sum(a,axis = 0)
c

array([14,  7,  9, 10])

In [51]:
v = np.sum(a,axis = 1)
v

array([ 8,  8, 12, 12])

In [ ]:
array = np.random.randint  (1, 11, size=(3, 3))
row_array = np.random.randint(1, 11, size=(3,))
print("Original array:")
print(array)
print("1D array:")
print(row_array)

Original array:
[[2 6 5]
 [7 6 9]
 [9 3 2]]
1D array:
[2 9 7]


In [60]:
array + row_array

array([[ 4, 15, 12],
       [ 9, 15, 16],
       [11, 12,  9]])

In [61]:
array + row_array[:,np.newaxis]

array([[ 4,  8,  7],
       [16, 15, 18],
       [16, 10,  9]])

In [57]:
a = np.newaxis

In [62]:
import numpy as np

array = np.random.randint(1, 11, size=(3, 3))
row_array = np.random.randint(1, 11, size=(3,))

# Adding without newaxis
result1 = array + row_array

# Adding with newaxis
result2 = array + row_array[:, np.newaxis]

print("Array:\n", array)
print("Row array:\n", row_array)
print("Result without newaxis:\n", result1)
print("Result with newaxis:\n", result2)


Array:
 [[10  3  4]
 [ 4 10  3]
 [ 2 10  8]]
Row array:
 [6 6 1]
Result without newaxis:
 [[16  9  5]
 [10 16  4]
 [ 8 16  9]]
Result with newaxis:
 [[16  9 10]
 [10 16  9]
 [ 3 11  9]]


### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.

In [64]:
np.linalg.det(array)

502.00000000000074

In [65]:
np.linalg.inv(array)

array([[ 0.09960159,  0.03187251, -0.06175299],
       [-0.05179283,  0.14342629, -0.02788845],
       [ 0.03984064, -0.187251  ,  0.1752988 ]])

In [66]:
np.linalg.eig(array)

EigResult(eigenvalues=array([17.7740466+0.j        ,  5.1129767+1.44944712j,
        5.1129767-1.44944712j]), eigenvectors=array([[ 0.54065875+0.j        , -0.50081923-0.25057211j,
        -0.50081923+0.25057211j],
       [ 0.53022148+0.j        , -0.13108363+0.16621358j,
        -0.13108363-0.16621358j],
       [ 0.65311048+0.j        ,  0.80098929+0.j        ,
         0.80098929-0.j        ]]))

In [68]:
array.reshape(1,9)

array([[10,  3,  4,  4, 10,  3,  2, 10,  8]])

In [69]:
array.flatten()

array([10,  3,  4,  4, 10,  3,  2, 10,  8])

In [70]:
# Create a NumPy array of shape (5, 5) filled with random integers
array = np.random.randint(1, 21, size=(5, 5))
print("Original array:")
print(array)

# Use fancy indexing to extract the elements at the corners of the array
corners = array[[0, 0, -1, -1], [0, -1, 0, -1]]
print("Corner elements:")
print(corners)

Original array:
[[19  2  2  1  5]
 [18  3  5 20 19]
 [12  3  4 12  8]
 [ 6  2  8  1 15]
 [12  4  9  8  2]]
Corner elements:
[19  5 12  2]


In [77]:
array[[0, 0, -1, -1],[0, -1, 0, -1]]

array([19,  5, 12,  2])

In [ ]:
array[array < 3]

array([2, 2, 1, 2, 1, 2])

2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

In [79]:
# Create a structured array with fields 'x' and 'y'
data_type = [('x', 'i4'), ('y', 'i4')]
data = np.array([(1, 2), (3, 4), (5, 6)], dtype=data_type)
print("Original array:")
print(data)

# Compute the Euclidean distance between each pair of points
distances = np.sqrt((data['x'][:, np.newaxis] - data['x'])**2 + (data['y'][:, np.newaxis] - data['y'])**2)
print("Euclidean distances:")
print(distances)

Original array:
[(1, 2) (3, 4) (5, 6)]
Euclidean distances:
[[0.         2.82842712 5.65685425]
 [2.82842712 0.         2.82842712]
 [5.65685425 2.82842712 0.        ]]


In [81]:
np.array([(1,2),(3,4)]).dtype

dtype('int32')

In [86]:
data_type = [("Name","U10"),("Age","i4")]
a = np.array(
    [("Sam",10),("Clary",12)]
    ,dtype=data_type)

In [89]:
a["Age"][0]

10

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.

In [101]:
import numpy.ma as ma
a = np.arange(1,10).reshape(3,3)

In [102]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [103]:
ma.masked_greater(a,10)[0]

masked_array(data=[1, 2, 3],
             mask=False,
       fill_value=999999)

In [104]:
ma.masked_greater(a,10).count()

9

2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [105]:
ma.diagonal(a)

masked_array(data=[1, 5, 9],
             mask=False,
       fill_value=999999)

In [106]:
ma.masked_array(a,a>8)

masked_array(
  data=[[1, 2, 3],
        [4, 5, 6],
        [7, 8, --]],
  mask=[[False, False, False],
        [False, False, False],
        [False, False,  True]],
  fill_value=999999)

In [109]:
import numpy as np

array = np.eye(3, dtype=bool)
print(array)


[[ True False False]
 [False  True False]
 [False False  True]]


In [111]:
masked = ma.masked_array(a,np.eye(3,dtype=bool))

In [114]:
masked.filled(np.mean(masked))

array([[5, 2, 3],
       [4, 5, 6],
       [7, 8, 5]])

In [116]:
import pandas as pd

In [136]:
df = pd.DataFrame(np.arange(1,21).reshape(10,2),columns=[00,11])

In [137]:
df

0   11
0   1   2
1   3   4
2   5   6
3   7   8
4   9  10
5  11  12
6  13  14
7  15  16
8  17  18
9  19  20

In [127]:
df.set_index(["B"], inplace=True)
print("DataFrame with new index:")
print(df)

DataFrame with new index:
Empty DataFrame
Columns: []
Index: [2, 4, 6, 8, 10, 12, 14, 16, 18, 20]


In [146]:
# Create a Pandas DataFrame with specified columns and index
df = pd.DataFrame(np.random.randint(1, 100, size=(3, 3)), columns=['A', 'B', 'C'], index=['X', 'Y', 'Z'])
print("Original DataFrame:")
print(df)

# Access the element at row 'Y' and column 'B'
element = df.at['Y', 'B']
print("Element at row 'Y' and column 'B':", element)

Original DataFrame:
    A   B   C
X  48  16  85
Y  85  36  55
Z   2  39  82
Element at row 'Y' and column 'B': 36


In [ ]:
element = df.iat[0,1]   #access it without the name of the column but with the index of the column

In [148]:
element

16

### Assignment 3: Data Cleaning

1. Create a Pandas DataFrame with 3 columns and 5 rows filled with random integers. Introduce some NaN values. Fill the NaN values with the mean of the respective columns.

In [154]:
df = pd.DataFrame([
                    {"Name":"Abeer","Age":22,"Salary":20000},
                   {"Name":"Dodo","Age":32,"Salary":40000},
                   {"Name":"Mazen","Age":32,"Salary":23300},
                   {"Name":"Mn","Age":None,"Salary":23100},
                   {"Name":"Mazen","Age":32,"Salary":None}
                   ])

In [160]:
df.isnull().sum()

Name      0
Age       1
Salary    1
dtype: int64

In [162]:
df["Salary"].fillna(df["Salary"].mean())

0    20000.0
1    40000.0
2    23300.0
3    23100.0
4    26600.0
Name: Salary, dtype: float64

In [166]:
df["Age"].fillna(df["Age"].mean(),inplace=True)

C:\Users\IT SHOP\AppData\Local\Temp\ipykernel_24324\2595122914.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Age"].fillna(df["Age"].mean(),inplace=True)


In [169]:
df["Age"].mean()

29.5

In [172]:
df["Age"].fillna({"Age":df["Age"].mean()},inplace=True)

In [167]:
df.isnull().sum()

Name      0
Age       0
Salary    1
dtype: int64

### Assignment 4: Data Aggregation

1. Create a Pandas DataFrame with 2 columns: 'Category' and 'Value'. Fill the 'Category' column with random categories ('A', 'B', 'C') and the 'Value' column with random integers. Group the DataFrame by 'Category' and compute the sum and mean of 'Value' for each category.

In [ ]:
df = pd.DataFrame(
    data =
        {
        "Category":[np.random.choice(("A","B","C")) for _ in range(20)],
        "Value":[ i for i in np.arange(1,21)]}
        )
        

In [192]:
df

Category  Value
0         C      1
1         C      2
2         B      3
3         A      4
4         C      5
5         A      6
6         B      7
7         B      8
8         B      9
9         A     10
10        B     11
11        B     12
12        B     13
13        A     14
14        B     15
15        C     16
16        C     17
17        B     18
18        B     19
19        B     20

In [196]:
df.groupby("Category")["Value"].sum()

Category
A     34
B    135
C     41
Name: Value, dtype: int32

In [199]:
df = pd.DataFrame(
    data = {
        "category":np.random.choice(['A','B','C'],size= 20),
        "value":np.arange(1,21),
        "sales": np.random.choice(np.arange(10000,100000),size=20)
    }
)

In [200]:
df

category  value  sales
0         C      1  21957
1         A      2  31807
2         C      3  32068
3         C      4  69064
4         C      5  11712
5         B      6  44721
6         C      7  65919
7         B      8  82392
8         A      9  91650
9         A     10  81769
10        C     11  69305
11        B     12  57723
12        A     13  45393
13        B     14  38692
14        A     15  74870
15        C     16  63231
16        A     17  46631
17        C     18  44992
18        A     19  56436
19        A     20  29045

In [201]:
df.groupby("category")["sales"].sum()

category
A    457601
B    223528
C    378248
Name: sales, dtype: int32

### Assignment 5: Merging DataFrames

1. Create two Pandas DataFrames with a common column. Merge the DataFrames using the common column.

In [20]:
df1 = pd.DataFrame(
    {   "id":np.arange(1,21),
        "category":np.random.choice(["Mobile","Tablet","Laptop"],size=20),
        "Price":   np.arange(100,120)
    }
)
df1

id category  Price
0    1   Tablet    100
1    2   Laptop    101
2    3   Mobile    102
3    4   Mobile    103
4    5   Mobile    104
5    6   Mobile    105
6    7   Laptop    106
7    8   Tablet    107
8    9   Mobile    108
9   10   Laptop    109
10  11   Mobile    110
11  12   Mobile    111
12  13   Mobile    112
13  14   Tablet    113
14  15   Laptop    114
15  16   Tablet    115
16  17   Tablet    116
17  18   Laptop    117
18  19   Tablet    118
19  20   Mobile    119

In [21]:
df2 = pd.DataFrame(
    {   "id":      np.arange(1,21),
        "category":np.random.choice(["Mobile","Tablet","Laptop"],size=20),
        "countity":np.arange(1,21)
    }
)
df2

id category  countity
0    1   Tablet         1
1    2   Laptop         2
2    3   Laptop         3
3    4   Mobile         4
4    5   Tablet         5
5    6   Mobile         6
6    7   Laptop         7
7    8   Laptop         8
8    9   Mobile         9
9   10   Tablet        10
10  11   Laptop        11
11  12   Laptop        12
12  13   Tablet        13
13  14   Laptop        14
14  15   Tablet        15
15  16   Laptop        16
16  17   Mobile        17
17  18   Mobile        18
18  19   Laptop        19
19  20   Tablet        20

In [25]:
df1.merge(df2,how='inner')

id category  Price  countity
0   1   Tablet    100         1
1   2   Laptop    101         2
2   4   Mobile    103         4
3   6   Mobile    105         6
4   7   Laptop    106         7
5   9   Mobile    108         9

In [26]:
df1 = pd.DataFrame({'A': np.random.randint(1, 100, size=3), 'B': np.random.randint(1, 100, size=3)})
df2 = pd.DataFrame({'C': np.random.randint(1, 100, size=3), 'D': np.random.randint(1, 100, size=3)})

In [28]:
pd.concat([df1,df2],axis=1)

A   B   C   D
0  26  88  70  88
1   7  53  68  70
2  46  77  47  15

In [29]:
pd.concat([df1,df2],axis=0)

A     B     C     D
0  26.0  88.0   NaN   NaN
1   7.0  53.0   NaN   NaN
2  46.0  77.0   NaN   NaN
0   NaN   NaN  70.0  88.0
1   NaN   NaN  68.0  70.0
2   NaN   NaN  47.0  15.0

### Assignment 6: Time Series Analysis

1. Create a Pandas DataFrame with a datetime index and one column filled with random integers. Resample the DataFrame to compute the monthly mean of the values.

In [46]:
ind = pd.date_range(start='12-01-2023',end='2-01-2024')
ind.shape

(63,)

In [47]:
data = np.arange(1,64)
data.shape

(63,)

In [68]:
df = pd.DataFrame({"count":data},index=ind)

In [49]:
df

count
2023-12-01      1
2023-12-02      2
2023-12-03      3
2023-12-04      4
2023-12-05      5
...           ...
2024-01-28     59
2024-01-29     60
2024-01-30     61
2024-01-31     62
2024-02-01     63

[63 rows x 1 columns]

In [52]:
df2 = df.resample('M').mean()

C:\Users\IT SHOP\AppData\Local\Temp\ipykernel_10372\951061776.py:1: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  df2 = df.resample('M').mean()


In [51]:
df2

count
2023-12-31   16.0
2024-01-31   47.0
2024-02-29   63.0

2. Create a Pandas DataFrame with a datetime index ranging from '2021-01-01' to '2021-12-31' and one column filled with random integers. Compute the rolling mean with a window of 7 days.

In [ ]:
df = pd.date_range(start='12-01-2021',end='12-30-2021',freq='3d')
df

In [65]:
df = pd.date_range(start='12-01-2021',end='12-30-2021',periods=3)
df

DatetimeIndex(['2021-12-01 00:00:00', '2021-12-15 12:00:00',
               '2021-12-30 00:00:00'],
              dtype='datetime64[ns]', freq=None)

In [ ]:
df = pd.DataFrame({'Val':data},index=)

count
2023-12-01    NaN
2023-12-02    NaN
2023-12-03    NaN
2023-12-04    NaN
2023-12-05    NaN
...           ...
2024-01-28   56.0
2024-01-29   57.0
2024-01-30   58.0
2024-01-31   59.0
2024-02-01   60.0

[63 rows x 1 columns]

In [55]:
df11 = df.resample("7d").mean()

In [56]:
df11

count
2023-12-01    4.0
2023-12-08   11.0
2023-12-15   18.0
2023-12-22   25.0
2023-12-29   32.0
2024-01-05   39.0
2024-01-12   46.0
2024-01-19   53.0
2024-01-26   60.0

In [87]:
date_rng = pd.date_range(start='2021-01-01', end='2021-12-31', freq='D')
df = pd.DataFrame(date_rng, columns=['date'])
df['data'] = np.random.randint(0, 100, size=(len(date_rng)))
df

date  data
0   2021-01-01    25
1   2021-01-02    61
2   2021-01-03    37
3   2021-01-04    14
4   2021-01-05     8
..         ...   ...
360 2021-12-27     1
361 2021-12-28    74
362 2021-12-29    15
363 2021-12-30    79
364 2021-12-31    53

[365 rows x 2 columns]

In [88]:
df.set_index(['date'],inplace=True)
df

data
date            
2021-01-01    25
2021-01-02    61
2021-01-03    37
2021-01-04    14
2021-01-05     8
...          ...
2021-12-27     1
2021-12-28    74
2021-12-29    15
2021-12-30    79
2021-12-31    53

[365 rows x 1 columns]

In [77]:
df.rolling(window=7).mean()

data
date                 
2021-01-01        NaN
2021-01-02        NaN
2021-01-03        NaN
2021-01-04        NaN
2021-01-05        NaN
...               ...
2021-12-27  60.285714
2021-12-28  70.142857
2021-12-29  68.000000
2021-12-30  63.285714
2021-12-31  65.714286

[365 rows x 1 columns]

In [91]:
df['data']

date
2021-01-01    25
2021-01-02    61
2021-01-03    37
2021-01-04    14
2021-01-05     8
              ..
2021-12-27     1
2021-12-28    74
2021-12-29    15
2021-12-30    79
2021-12-31    53
Name: data, Length: 365, dtype: int32

In [113]:
arrays = [['A', 'A', 'B', 'B'], 
          ['one', 'two', 'one', 'two']]

index = pd.MultiIndex.from_arrays(arrays,names=("category","subcategory"))
df = pd.DataFrame(np.random.randint(1, 100, size=(4, 3)), index=index, columns=['Value1', 'Value2', 'Value3'])


In [114]:
df

Value1  Value2  Value3
category subcategory                        
A        one              84      18       3
         two              67       3      54
B        one              31      36      89
         two              15      77      63

In [119]:
df.groupby(['category','subcategory']).sum()

Value1  Value2  Value3
category subcategory                        
A        one              84      18       3
         two              67       3      54
B        one              31      36      89
         two              15      77      63

In [120]:
# Create a Pandas DataFrame with MultiIndex consisting of 'Category' and 'SubCategory'
arrays = [['A', 'A', 'B', 'B', 'C', 'C'], ['one', 'two', 'one', 'two', 'one', 'two']]
index = pd.MultiIndex.from_arrays(arrays, names=('Category', 'SubCategory'))
df = pd.DataFrame(np.random.randint(1, 100, size=(6, 3)), index=index, columns=['Value1', 'Value2', 'Value3'])
print("MultiIndex DataFrame:")
print(df)

# Compute the sum of values for each 'Category' and 'SubCategory'
sum_values = df.groupby(['Category', 'SubCategory']).sum()
print("Sum of values:")
print(sum_values)

MultiIndex DataFrame:
                      Value1  Value2  Value3
Category SubCategory                        
A        one              18       5      81
         two              87      31      27
B        one              86      63      77
         two              64      27       2
C        one              19      39      71
         two              64      44      92
Sum of values:
                      Value1  Value2  Value3
Category SubCategory                        
A        one              18       5      81
         two              87      31      27
B        one              86      63      77
         two              64      27       2
C        one              19      39      71
         two              64      44      92
